import { describe, expect, it } from "vitest";
import { getApcaScore, getApcaTier } from "./index";

// All Lc values below were generated by running apca-w3's own
// APCAcontrast/sRGBtoY directly against these RGB pairs (not hand-computed) -
// this is math this repo doesn't own, so a wrong hand-derived expected value
// would silently pass a broken implementation.
describe("getApcaTier", () => {
	it("treats 36px as the body tier (boundary is exclusive)", () => {
		expect(getApcaTier(36)).toBe("body");
	});

	it("treats 37px as the large tier", () => {
		expect(getApcaTier(37)).toBe("large");
	});
});

describe("getApcaScore", () => {
	it("passes the body tier for a pair well above Lc 75", () => {
		// #333333 on #dddddd -> Lc ~78.72
		const result = getApcaScore([0x33, 0x33, 0x33], [0xdd, 0xdd, 0xdd], 16, false);
		expect(result.tier).toBe("body");
		expect(result.requiredLc).toBe(75);
		expect(result.maxLc).toBeNull();
		expect(result.lc).toBeCloseTo(78.72, 1);
		expect(result.meetsMinimum).toBe(true);
	});

	it("fails the body tier for a pair below Lc 75", () => {
		// #767676 on white -> Lc ~71.57
		const result = getApcaScore([0x76, 0x76, 0x76], [255, 255, 255], 16, false);
		expect(result.tier).toBe("body");
		expect(result.lc).toBeCloseTo(71.57, 1);
		expect(result.meetsMinimum).toBe(false);
	});

	it("passes the large tier for a pair between the Lc 45 floor and Lc 90 ceiling", () => {
		// #767676 on white -> Lc ~71.57, fails body but sits comfortably inside large's 45-90 range
		const result = getApcaScore([0x76, 0x76, 0x76], [255, 255, 255], 40, false);
		expect(result.tier).toBe("large");
		expect(result.requiredLc).toBe(45);
		expect(result.maxLc).toBe(90);
		expect(result.meetsMinimum).toBe(true);
	});

	it("fails the large tier for a pair below the Lc 45 floor", () => {
		// #bbbbbb on white -> Lc ~36.72
		const result = getApcaScore([0xbb, 0xbb, 0xbb], [255, 255, 255], 40, false);
		expect(result.tier).toBe("large");
		expect(result.lc).toBeCloseTo(36.72, 1);
		expect(result.meetsMinimum).toBe(false);
	});

	it("fails the large tier for a pair above the Lc 90 ceiling (Bronze's halation cap on huge headlines)", () => {
		// black on white -> Lc ~106.04, comfortably exceeds the large tier's 90 cap
		const result = getApcaScore([0, 0, 0], [255, 255, 255], 40, false);
		expect(result.tier).toBe("large");
		expect(result.lc).toBeCloseTo(106.04, 1);
		expect(result.meetsMinimum).toBe(false);
	});

	it("stores the raw signed Lc without normalizing polarity", () => {
		// white on black -> Lc ~-107.88 (negative), vs. black-on-white's ~106.04 (positive)
		const result = getApcaScore([255, 255, 255], [0, 0, 0], 16, false);
		expect(result.lc).toBeCloseTo(-107.88, 1);
	});

	it("fails both tiers for near-identical colors", () => {
		const result = getApcaScore([0x88, 0x88, 0x88], [0x7f, 0x7f, 0x7f], 16, false);
		expect(result.lc).toBeCloseTo(0, 1);
		expect(result.meetsMinimum).toBe(false);
	});

	it("falls back to a safe non-throwing default for an invalid fontSize", () => {
		const result = getApcaScore([0, 0, 0], [255, 255, 255], NaN, false);
		expect(result).toEqual({
			lc: 0,
			tier: "body",
			requiredLc: 75,
			maxLc: null,
			meetsMinimum: false,
		});
	});

	it("falls back to a safe non-throwing default for a symbol fontSize", () => {
		const result = getApcaScore([0, 0, 0], [255, 255, 255], Symbol("mixed"), false);
		expect(result).toEqual({
			lc: 0,
			tier: "body",
			requiredLc: 75,
			maxLc: null,
			meetsMinimum: false,
		});
	});

	it("ignores isBold - Bronze's tiers are weight-independent (locks in today's documented behavior)", () => {
		const normal = getApcaScore([0x33, 0x33, 0x33], [0xdd, 0xdd, 0xdd], 16, false);
		const bold = getApcaScore([0x33, 0x33, 0x33], [0xdd, 0xdd, 0xdd], 16, true);
		expect(bold).toEqual(normal);
	});
});
